version: 0.0
os: linux
files:
  - source: /project_fault.zip
    destination: /home/ec2-user/ProjectFault
permissions:
  - object: /home/ec2-user/ProjectFault/scripts
    pattern: +x
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
